image: atlassian/default-image:3

pipelines:
  default:
    - step:
        name: Build and Push Docker Image
        services:
          - docker
        script:
          - docker build -t $DOCKER_HUB_USERNAME/my-node-app:latest .
          - echo $DOCKER_HUB_PASSWORD | docker login -u $DOCKER_HUB_USERNAME --password-stdin
          - docker push $DOCKER_HUB_USERNAME/my-node-app:latest
